### ISSUE TITLE
Deriving convergence state

### ISSUE THREAD

**Issue by cieske** [xue-pai/UltraGCN#1]
Hi! Thanks for the great work. There are two convergence states in eq.9 and eq.16 in your paper, may I ask the process of deriving \beta_{u,i} and \omega_{i,j}?

**Comment by kyriemao** [comment]
Hi cieske,

For eq.9, it is derived from eq.8 by transposing the "\frac{1}{d_u + 1} e_u" in the  right side to the left side, and you can get "\frac{d_u}{d_u + 1} e_u = ...e_i". Then multiply "\frac{d_u + 1}{d_u}" to the both sides, and you can get eq.9.

For eq.16, its derivation is the same as eq.9. You can first write an equation like eq.8 as "e_i = \frac{G_{i, i}}{g_i} e_i + \frac{G_{i, k}}{\sqrt{g_i}\sqrt{g_k}} e_k". Then  you will get eq.16.

**Comment by kyriemao** [comment]
> Hi! Thanks for the great work. There are two convergence states in eq.9 and eq.16 in your paper, may I ask the process of deriving \beta_{u,i} and \omega_{i,j}?

Hi cieske,

For eq.9, it is derived from eq.8 by transposing the "\frac{1}{d_u + 1} e_u" in the right side to the left side, and you can get "\frac{d_u}{d_u + 1} e_u = ...e_i". Then multiply "\frac{d_u + 1}{d_u}" to the both sides, and you can get eq.9.

For eq.16, its derivation is the same as eq.9. You can first write an equation like eq.8 as "e_i = \frac{G_{i, i}}{g_i} e_i + \frac{G_{i, k}}{\sqrt{g_i}\sqrt{g_k}} e_k". Then you will get eq.16.

**Comment by cieske** [comment]
I understand. Thank you for your reply!

**Comment by yuanzhongfei** [comment]
> > Hi! Thanks for the great work. There are two convergence states in eq.9 and eq.16 in your paper, may I ask the process of deriving \beta_{u,i} and \omega_{i,j}?
> 
> Hi cieske,
> 
> For eq.9, it is derived from eq.8 by transposing the "\frac{1}{d_u + 1} e_u" in the right side to the left side, and you can get "\frac{d_u}{d_u + 1} e_u = ...e_i". Then multiply "\frac{d_u + 1}{d_u}" to the both sides, and you can get eq.9.
> 
> For eq.16, its derivation is the same as eq.9. You can first write an equation like eq.8 as "e_i = \frac{G_{i, i}}{g_i} e_i + \frac{G_{i, k}}{\sqrt{g_i}\sqrt{g_k}} e_k". Then you will get eq.16.

代码里面实现跟第一个user-item实现是一样的，没看懂给出这个公式有什么用
