### ISSUE TITLE
ii_constraint_mat 占用内存巨大

### ISSUE THREAD

**Issue by jzm-123** [xue-pai/UltraGCN#10]

**Comment by kyriemao** [comment]
ii_constraint_mat的shape是(num_items, num_neighbors)，这个不是很大吧？

**Comment by jzm-123** [comment]
代码里做dot的维度和constraint_mat维度一致，不是（items，neighbor）这个维度



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月23日(周四) 晚上11:07
收件人: ***@***.***&gt;;
抄送: "Zhenming ***@***.******@***.***&gt;;
主题: Re: [xue-pai/UltraGCN] ii_constraint_mat 占用内存巨大 (Issue #10)




 
ii_constraint_mat的shape是(num_items, num_neighbors)，这个不是很大吧？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kyriemao** [comment]
嗯是的，开始构建的时候确实需要较多内存，但在这几个学术数据集上，还可以接受吧。。 Item最多的Amazon-Books（9w item）大约需要60G内存

**Comment by Joinn99** [comment]
这里的内存占用主要是`all_ii_constraint_mat`导致的吧，它的维度是(n_items, n_items)。而下方使用这个mat时是循环调用每一行，所以完全可以在循环内部实时构造，这样维度是(n_items,)。
因为这一步只执行一次，所以我提交pr时并没有改这一部分，不过应该是很容易改的。

**Comment by jzm-123** [comment]
对的，但我发现mask这个矩阵占的内存也比较大，有什么好的方法可以解决吗

**Comment by kyriemao** [comment]
mask矩阵是稀疏的，资源有限的话可以换用稀疏矩阵来存mask

> 对的，但我发现mask这个矩阵占的内存也比较大，有什么好的方法可以解决吗

**Comment by jzm-123** [comment]
可以提供利用稀疏矩阵来存mask的代码示例吗

**Comment by TedSIWEILIU** [comment]
> 



> 代码里做dot的维度和constraint_mat维度一致，不是（items，neighbor）这个维度

他这个模型的实现，是不是单卡根本跑不了啊？我一到test forward那里就直接爆内存了。

**Comment by kyriemao** [comment]
> 

爆内存和单卡与否没关系。你的内存是多大？跑的哪个数据集？

**Comment by kyriemao** [comment]
> 可以提供利用稀疏矩阵来存mask的代码示例吗

把mask转换成numpy稀疏矩阵存储，然后在test的时候把mask[batch_users]再转成稠密的和score矩阵做相加运算即可。代码参考http://liao.cpython.org/scipy03.html

**Comment by TedSIWEILIU** [comment]
> > 
> 
> 爆内存和单卡与否没关系。你的内存是多大？跑的哪个数据集？

不好意思，是我自己的实现有错误。修复以后可以跑了
