### ISSUE TITLE
settings of hyper-parameters w1,...,w4

### ISSUE THREAD

**Issue by xiransong** [xue-pai/UltraGCN#12]
Hi! What is the relationship between the hyper-parameter lambda described in your paper and the variables w1, w2, w3, w4 in the code?
The paper reported that "We tune lambda in [0.2, 0.4, ..., 1.2, 1.4], ...". However, in many dataset_name_config.ini files, some w1,...,w4 are set to 1e-8 or 1e-7.
For example, in amazon_config.ini:
#L = -(w1 + w2*\beta)) * log(sigmoid(e_u e_i)) - \sum_{N-} (w3 + w4*\beta) * log(sigmoid(-e_u e_i'))
w1=1e-8
w2=1
w3=1
w4=1e-8

Thank you!

**Comment by kyriemao** [comment]
Hi, Thanks for your attention.

For UltraGCN_base, the loss in the paper is written as L = L_O + lambda * L_C, so w2 and w4 are the lambda.  If exactly follow the original paper, w2 and w4 should always be set to the same value as they are both the lambda. But in this implementation, we separate the lambda to w2 and w4 for the losses of positive and negative samples respectively, which is more flexible.
