### ISSUE TITLE
论文公式

### ISSUE THREAD

**Issue by yuanzhongfei** [xue-pai/UltraGCN#13]
你好，
1.请问论文中的传递公式3，4 怎么来的呢？
2.还有代码实现时item-item的系数计算是跟user-item的那个系数计算一样的，不太明白论文给出那个计算item-item计算公式有什么用处?
谢谢

**Comment by kyriemao** [comment]
1.公式3,4就是公式2展开到每个节点上来看的时候的表示，每个节点会聚合自己（加了self-loop的情况下）和周围邻居的信息。
2. 你说的item-item计算公式是指公式16吗？item-item和user-item的计算方式就是一样的，区别只是用公式16的omega替换user-item的beta。

**Comment by yuanzhongfei** [comment]
哦哦，那个公式2的的展开有推导过程没呢

**Comment by kyriemao** [comment]
把E, D, A这三个矩阵都写出来，按公式2做基本的矩阵乘法，就可以发现和公式3,4一样了。

**Comment by yuanzhongfei** [comment]
> 把E, D, A这三个矩阵都写出来，按公式2做基本的矩阵乘法，就可以发现和公式3,4一样了。

谢谢
