### ISSUE TITLE
您好，请教一下时间复杂度的计算

### ISSUE THREAD

**Issue by ithok** [xue-pai/UltraGCN#15]
作者您好，感谢您的工作！
想请教一下在原文的3.3节中对时间复杂度的推导里得到的结果
O（（K+R+1）*|A+|*(d^2+1））的具体推导过程？主要的问题是在d^2上，这里我预先自己推的结果是(d+1)(没有平方)，粗浅的理解是算损失只需要计算d维度的乘法，同时针对每个交互样本计算一次对应系数。
能否请教一下具体的过程呢？

**Comment by kyriemao** [comment]
Hi,

Thanks for your correction! It should be (d + 1) not (d^2 + 1). I'll revise it.
