### ISSUE TITLE
Normalized or NOT？

### ISSUE THREAD

**Issue by junkangwu** [xue-pai/UltraGCN#16]
Hi,
Recently I came across your paper ( a nice work), your paper explained eq. 10 with "We normalized the embeddings to unit vectors and then maximized the  dot product of the both terms". However, I can not find "normalization" operation in your codes. May I ask you about this part?
Thanks a lot

**Comment by kyriemao** [comment]
Hi Junkang, 

Thanks for your question! Yes, as we wrote in the paper, the normalized embeddings seem to be more reasonable.  The results reported in the paper are based on the normalized embeddings. But we later find comparable or even better results can be achieved without normalization (as the current code shows), so we remove the normalization in the code and you can add it back to achieve similar performance.

Best
