### ISSUE TITLE
ml-1m数据集处理问题

### ISSUE THREAD

**Issue by BIAOBIAO12138** [xue-pai/UltraGCN#18]
作者你好，请问方便给一下数据集处理代码吗，我在复现过程中ml-1m数据集出现问题

**Comment by zhujiem** [comment]
数据集使用已有论文已经处理好的，见 https://github.com/Wenhui-Yu/LCFN/tree/master/dataset/Movielens

**Comment by zhujiem** [comment]
> @BIAOBIAO12138 Hello, 请问您的 ML-1M可以复现吗？ @kyriemao 作者能提供一个 ML-1M中跟论文中一致的，超参配置吗？ 现在的ml-1m_config.ini有的参数跟文章的Parameter Settings.不一致，我这边根据文章中Parameter Settings无法复现论文结果。谢谢！

论文复现已代码和配置文件为准。

**Comment by enoche** [comment]
> 

谢谢回复！数据集这个repo中已经自带了！

代码和论文配置不一致 怎么处理？  
如果在新的数据集通过论文配置还是怎么配置？

**Comment by BIAOBIAO12138** [comment]
thank you

**Comment by kyriemao** [comment]
> > 果。谢谢！
> 
> 论文复现已代码和配置文件为准。
以代码配置为准。新的数据集可以某个统计特性相近的数据集的配置为起点，然后调参
