### ISSUE TITLE
BASELINE复现问题

### ISSUE THREAD

**Issue by junkangwu** [xue-pai/UltraGCN#19]
Hi, 请问文章中report的baseline是有开源框架进行复现嘛？能否分享一下经验谢谢！

**Comment by junkangwu** [comment]
@kyriemao 比如文中那些deepwalk,node2vec等传统方法，请问是否有参考源码或者工具之类的，感谢

**Comment by kyriemao** [comment]
Yes, you can refer to [OpenNE](https://github.com/thunlp/OpenNE) for deepwalk, LINE and node2vec.

**Comment by kyriemao** [comment]
> @kyriemao 比如文中那些deepwalk,node2vec等传统方法，请问是否有参考源码或者工具之类的，感谢
Yes, you can refer to [OpenNE](https://github.com/thunlp/OpenNE) for deepwalk, LINE and node2vec.

**Comment by junkangwu** [comment]
> > @kyriemao 比如文中那些deepwalk,node2vec等传统方法，请问是否有参考源码或者工具之类的，感谢
> > Yes, you can refer to [OpenNE](https://github.com/thunlp/OpenNE) for deepwalk, LINE and node2vec.



> > @kyriemao 比如文中那些deepwalk,node2vec等传统方法，请问是否有参考源码或者工具之类的，感谢
> > Yes, you can refer to [OpenNE](https://github.com/thunlp/OpenNE) for deepwalk, LINE and node2vec.

请问这种都只能靠自己复现嘛？似乎这个仓库不是针对推荐场景的，以及NIA-GCN LR-GCN CML 等均无对应的数据集效果，请问作者您是依次自己复现的吗？

**Comment by zhujiem** [comment]
大部分baseline复现放这里了。https://github.com/openbenchmark/BARS/tree/master/candidate_matching/benchmarks
DeepWalk那些是用github版本自己跑的，但是还没整理。

**Comment by junkangwu** [comment]
> 大部分baseline复现放这里了。https://github.com/openbenchmark/BARS/tree/master/candidate_matching/benchmarks DeepWalk那些是用github版本自己跑的，但是还没整理。

好的谢谢， 我去学习一下

**Comment by junkangwu** [comment]
> 大部分baseline复现放这里了。https://github.com/openbenchmark/BARS/tree/master/candidate_matching/benchmarks DeepWalk那些是用github版本自己跑的，但是还没整理。

您好，我在学习 baseline整理的benchmark的时候，我发现很多链接都不存在了，请问这个benchmark还在维护嘛？如 [CML](https://github.com/openbenchmark/BARS/tree/88d3a0faa4565e975141ae89a52d35d3a8b56eda/candidate_matching/benchmarks/CML/CML_yelp18_x1)  
> The benchmark is implemented based on the original CML code released by the authors at https://github.com/changun/CollMetric/tree/d9026cfce7c6e8dd2640b842ad524b61031b29ac, we use the version with commit hash: d9026cf. We also made the following modifications for our benchmarking. These changes can be viewed via a diff comparison here: https://github.com/xue-pai/Open-CF-Benchmarks/compare/5415b7...1d6bd6?diff=split 
上述步骤链接显示404 （ https://github.com/xue-pai/Open-CF-Benchmarks/compare/5415b7...1d6bd6?diff=split ）

**Comment by kyriemao** [comment]
> https://github.com/xue-pai/Open-CF-Benchmarks/compare/5415b7...1d6bd6?diff=split

哪一个链接是404？这两个链接我都可以打开呀

**Comment by junkangwu** [comment]
> 

已发送邮箱

**Comment by zhujiem** [comment]
Open-CF-Benchmark改为Open-Match-Benchmark试一下，或者自己git diff一下
