### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by GabyUSTC** [xue-pai/UltraGCN#2]
Hi authors, I noted that you tested your UltraGCN model on another three datasets: MovieLens-1M, Amazon-CDs, Amazon-Electronics. Could you please provide those datasets so that we can better follow your work? Much appreciated.

**Comment by kyriemao** [comment]
> Hi authors, I noted that you tested your UltraGCN model on another three datasets: MovieLens-1M, Amazon-CDs, Amazon-Electronics. Could you please provide those datasets so that we can better follow your work? Much appreciated.
Hi,
Thanks for your attention. We have now released the datasets and benchmarks for these three datasets (MovieLens-1M, Amazon-CDs, Amazon-Electronics).  Hope it can help.
