### ISSUE TITLE
Hyper-parameter lambda/gamma   w1,...,w4

### ISSUE THREAD

**Issue by enoche** [xue-pai/UltraGCN#20]
Hi, thanks for sharing the source code for reproducing your results.
However, I am confused with mapping the hyper-parameters between your code and paper:
1. lambda is placed on L_C for constraint loss in paper (Eq. 12, 18) for U-I relationships.
   But, in code, lambda is used for L_2 loss?

  lambda's setting is within [0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4] in paper, but in code we have gamma=1e-4?

2. gamma for I-I relationships in paper (Eq. 18) and is inline with the code.
    And its setting [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3,3.5] in paper. However, in code, we observe gamma with 5e-4 or 1e-3 (ML-1M).
  Should we follow the paper for its settings?

3. w1, ..., w4 are used for generating omega coefficient, but you have mentioned they are related with lambda in previous issue [12?](https://github.com/xue-pai/UltraGCN/issues/12)

**Comment by kyriemao** [comment]
Hi,

1. 

> Hi, thanks for sharing the source code for reproducing your results. However, I am confused with mapping the hyper-parameters between your code and paper:
> 
> 1. lambda is placed on L_C for constraint loss in paper (Eq. 12, 18) for U-I relationships.
>    But, in code, lambda is used for L_2 loss?
> 
> lambda's setting is within [0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4] in paper, but in code we have gamma=1e-4?
> 
> 2. gamma for I-I relationships in paper (Eq. 18) and is inline with the code.
>    And its setting [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3,3.5] in paper. However, in code, we observe gamma with 5e-4 or 1e-3 (ML-1M).
>    Should we follow the paper for its settings?
> 3. w1, ..., w4 are used for generating omega coefficient, but you have mentioned they are related with lambda in previous issue [12?](https://github.com/xue-pai/UltraGCN/issues/12)

Hi,
Thanks for your questions. Please see Line 363 that lambda is placed on L_C but not L_2 loss. As mentioned in issue [12](https://github.com/xue-pai/UltraGCN/issues/12), we further separate the lambda to w2 and w4 for the losses of positive and negative samples respectively to make the parameter settings more flexible, which is a little different from the original paper. We suggest using the parameter settings of this repo but not the paper reported.

**Comment by enoche** [comment]
Thanks for your reply.
Sure, it is okay to use two variables to denote one variable.

1. I acknowledge that $\lambda$ is placed on $L_I$ in Line 363, noting not on $L_C$, which seems not inline with Eq. 18 in paper.

2. $L_C$ not implemented in code, instead we use the norm loss in Line 362, which is also inconsistent  with the paper Eq. 18?

**Comment by kyriemao** [comment]
> Thanks for your reply. Sure, it is okay to use two variables to denote one variable.
> 
> 1. I acknowledge that λ is placed on LI in Line 363, noting not on LC, which seems not inline with Eq. 18 in paper.
> 2. LC not implemented in code, instead we use the norm loss in Line 362, which is also inconsistent  with the paper Eq. 18?

Hi,
Sorry, I was wrong about my last answer. For your questions:
1. You're right. The parameter notions in the code are inconsistent with those in the paper. The lambda parameter in the paper is actually the w2 and w4 parameters in the code. Besides, the omega_weight used in cal_loss_L (line 318) actually denotes the beta in the paper (eq.12) but not the omega in the paper (eq. 17).  The omega in the paper (eq. 17) is denoted by ``self.ii_constraint_mat'' in the code.

2. L_C is implemented in the ``cal_loss_L'' function, where we use (w1, w2, w3, w4) to control the weights of L_O (w1 and w3) and L_C (w2 and w4) of the paper. 

Please let me know if you have any question. I am sorry for the confusion caused by my inconsistent usage of parameter names.

**Comment by enoche** [comment]
Okay, in this way, $L_C$ and $L_O$ would be the same.  May I have you help to mapping $L_C$, $L_O$ and $L_I$ with the functions in your code? Thanks.

**Comment by kyriemao** [comment]
> Okay, in this way, LC and LO would be the same. May I have you help to mapping LC, LO and LI with the functions in your code? Thanks.

Sure, L_C and L_O are computed in the ''cal_loss_L'' function in an integrated way. The integration is performed in the line 301 and line 308.   L_I is computed in ''cal_loss_I'' function.
