### ISSUE TITLE
关于对比实验的问题

### ISSUE THREAD

**Issue by BlueGhostZ** [xue-pai/UltraGCN#21]
对比实验采用了NIA-GCN，据我所知该方法并未开源，请问作者是自己复现该工作的吗，或是通过其他途径获取的代码，非常感谢。

**Comment by kyriemao** [comment]
> 对比实验采用了NIA-GCN，据我所知该方法并未开源，请问作者是自己复现该工作的吗，或是通过其他途径获取的代码，非常感谢。

NIA-GCN是自己按论文描述实现的
