### ISSUE TITLE
关于Loss的问题

### ISSUE THREAD

**Issue by D-JI-Feng** [xue-pai/UltraGCN#23]
作者你好，我在论文中看到，loss是这样求的：L = Lo + lamda_ * Lc + gamma_ * Li，但在代码里，似乎loss是这样求的：L = Lc + gamma_ * parameters.norm_loss() + lamda_ * Li。有些不一致，可以解释一下吗？

**Comment by kyriemao** [comment]
Hi,

Please refer to this issue https://github.com/xue-pai/UltraGCN/issues/12.
