### ISSUE TITLE
Confusion about the distinction between 'pos_weight' and 'pos_weight' in get_omegas()

### ISSUE THREAD

**Issue by juhyein** [xue-pai/UltraGCN#25]
Hello,

I am having trouble understanding the difference between the variable names 'pos_weight' and 'pos_weight' in the get_omegas function. Based on the code, it appears that the function returns the weight by concatenating 'pow_weight' and 'neg_weight'. However, when self.w2 > 0, it seems that the calculated variable is named 'pos_weight'. Could you please confirm if this is a typographical error?

Thank you.

**Comment by zhujiem** [comment]
@kyriemao

**Comment by kyriemao** [comment]
> Hello,
> 
> I am having trouble understanding the difference between the variable names 'pos_weight' and 'pos_weight' in the get_omegas function. Based on the code, it appears that the function returns the weight by concatenating 'pow_weight' and 'neg_weight'. However, when self.w2 > 0, it seems that the calculated variable is named 'pos_weight'. Could you please confirm if this is a typographical error?
> 
> Thank you.

Thanks for pointing out. This should be a typographical error and has been revised.
