### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by mixiamcc** [xue-pai/UltraGCN#26]
Hello, when I was executing the code, the following error was reported, could you please help guide the following
![image](https://github.com/xue-pai/UltraGCN/assets/50347836/e59039d3-7c65-40cc-b73e-1795088418fe)

**Comment by zhujiem** [comment]
UltraGCN was reproduced with the following enviornment. https://github.com/xue-pai/UltraGCN/issues/24

Could you provide your environment info?

**Comment by priyanshmathur** [comment]
I have used the same environment given in your ```readme.md```

python 3.7.9
pytorch 1.4.0
numpy 1.19.2
scipy 1.1.0
tensorboard 2.4.0

Would you like me to shift to #24 ? 

PS: I am working on MovieLens 1M dataset

**Comment by zhujiem** [comment]
Do you succeed in other datasets? Yelp18, Gowalla, or AmazonBooks

**Comment by priyanshmathur** [comment]
I honestly did not try them. 
I am interested in movie recommendation system and just tried it out for MovieLens 1M dataset

**Comment by kyriemao** [comment]
If you got the error: `IndexError: tensors used as indices must be long, byte or bool tensors`, you can modify the index variable with `.long()`. For example, you can change line 306 into
`torch.mul(self.constraint_mat['beta_uD'][users.long()], self.constraint_mat['beta_iD'][pos_items.long()]).to(device)`. 

Does this work?

**Comment by kyriemao** [comment]
> Hello, when I was executing the code, the following error was reported, could you please help guide the following ![image](https://user-images.githubusercontent.com/50347836/248461156-e59039d3-7c65-40cc-b73e-1795088418fe.png)



> Yes, I am facing the same issue. Have you figured out anything yet?
> 
> @kyriemao Can you please help with this issue I have created the environment as mentioned.


If you got the error:
`IndexError: tensors used as indices must be long, byte or bool tensors`, you can modify the index variable with `.long()`.

For example, you can change Line 306 into `pos_weight = torch.mul(self.constraint_mat['beta_uD'][users.long()], self.constraint_mat['beta_iD'][pos_items.long()]).to(device)`.

Does this work?

**Comment by zhujiem** [comment]
Please try the fix: https://github.com/reczoo/RecZoo/tree/main/matching/gnn/UltraGCN#faq
