### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors 

### ISSUE THREAD

**Issue by priyanshmathur** [xue-pai/UltraGCN#27]
I am facing the below error in ```main.py``` similar to #26  but on a different line 

ScreenShot:
![image](https://github.com/xue-pai/UltraGCN/assets/80464081/1a9e6379-e19e-4fce-a89e-70f33a633fc5)

This error is on a different line (313) and needs help to rectify.

Something I have done:

I> Changed line 313 to ```neg_weight = torch.mul(torch.repeat_interleave(self.constraint_mat['beta_uD'][users.long()], neg_items.size(1)), self.constraint_mat['beta_iD'][neg_items.flatten()]).to(device)```

Can you please solve this

I wanted to comment on #26 but was closed. Hence opening a new one

**Comment by stephenlin1234** [comment]
You can try using GPT

**Comment by zhujiem** [comment]
I guess it is still a issue caused by incompatible versions. You can follow https://github.com/xue-pai/UltraGCN/issues/24 to have a try.

**Comment by priyanshmathur** [comment]
DO you want me to try updating to the latest versions and try ?

**Comment by zhujiem** [comment]
Please try the fix: https://github.com/reczoo/RecZoo/tree/main/matching/gnn/UltraGCN#faq
