### ISSUE TITLE
How to derive w_ij

### ISSUE THREAD

**Issue by Kasonreal** [xue-pai/UltraGCN#4]
Hey, can you show how to derive w_ij in Eq(16) in detail? Thanks!

**Comment by kyriemao** [comment]
> Hey, can you show how to derive w_ij in Eq(16) in detail? Thanks!

For eq.16, its derivation is the same as eq.9. You can first write an equation like eq.8 as "e_i = \frac{G_{i, i}}{g_i} e_i + \frac{G_{i, k}}{\sqrt{g_i}\sqrt{g_k}} e_k". Then you will get eq.16.

**Comment by Kasonreal** [comment]
Got it. Thanks, bro. I will close this issue.
