### ISSUE TITLE
Could you tell me How did you test the previous models?

### ISSUE THREAD

**Issue by Lim-Sung-Jun** [xue-pai/UltraGCN#5]
thank you for your paper
I read LR-GCCF, NGCF papers before and the LR-GCCF result was better than NGCF
how did you test these 2 models? and how did you find the best hyperparamters of two models? 
could you tell me? I want to test models by myself.

**Comment by zhujiem** [comment]
Hello, all the results of baseline models can be found at https://openbenchmark.github.io/candidate-matching/

Notice: the NDCG of the LR-GCCF  paper was consistent with NGCF, but both are incorrect. NGCF has revised the code and results in its arxiv version. We report the correct one, consistent with NGCF's new version and LightGCN.

**Comment by Lim-Sung-Jun** [comment]
> Hello, all the results of baseline models can be found at https://openbenchmark.github.io/candidate-matching/
> 
> Notice: the NDCG of the LR-GCCF paper was consistent with NGCF, but both are incorrect. NGCF has revised the code and results in its arxiv version. We report the correct one, consistent with NGCF's new version and LightGCN.

NDCG of NGCF is incorrect and the NDCG of LR-GCCF changed correctly.
Do you mean you revised the code of NDCG of NGCF correctly?

below text is on https://github.com/newlei/LR-GCCF
**Note: the results of NGCF in our paper
Why is there a big gap between the NGCF results in the paper and the original NGCF? Since many researcher have consulted this issue, we explain here.
In short, the calculated NDCG in the original NGCF is not consistent with the original NDCG. We have fixed it and show the correct results. So there a big gap in the results of NGCF.
NDCG=DCG/IDCG. The maximum possible DCG is called Ideal DCG (IDCG), in other words, IDCG is the DCG value of the best ranking function on a dataset. so for a specific user in test data, the best ranking is unique, then the IDCG is unchanging. However, in NGCF code, the IDCG is changing. The calculation of the dcg_max(IDCG) depends on parameters r, but r is not the best ranking and will change according to the predicted of the model. Thus, the results of NGCF are based on a wrong implementation of NDCG.
You also can refer to the link and link is the follow-up work of NGCF authors, this link also explains problem of NDCG.
Note: If you have questions about NGCF, please contact the author of NGCF or create github issues under the official code~link.**


thank for your answer :)

**Comment by zhujiem** [comment]
@Lim-Sung-Jun  Sorry that I remembered wrongly. I just double-checked with the contributor of the experiments. The NDCG metric has been revised in the LR-GCCF code. We follow the same metric code as theirs. But we also added Recall to compute recall@K.

**Comment by zhujiem** [comment]
For your question, our results are based on the correct NDCG implementation of both.

**Comment by Lim-Sung-Jun** [comment]
> For your question, our results are based on the correct NDCG implementation of both.

thank for your reply!
