### ISSUE TITLE
卷积和损失函数

### ISSUE THREAD

**Issue by malajikuai** [xue-pai/UltraGCN#8]
作者您好，我是一名刚接触图卷积的小白，我对于这篇文章的理解是在保证性能的前提下提高模型的效率，因此你们去掉了卷积层，但是在loss函数里面加入约束项来替代卷积层。不知道你们有没有进行过同时使用这个函数和不去掉卷积层的实验，性能如何？不考虑效率的情况下。

**Comment by kyriemao** [comment]
我们没有试过这种做法，不过可能有提升，你可以试一下。
